export default function () {
    return [
        {title: 'Javascript: The Good Parts', pages:101 },
        {title: 'Harry Potter', pages: 39 },
        {title: 'The Dark Tower', pages: 85 },
        {title: 'Eloquent Ruby', pages: 1 }
    ];
}

//Application state is generated by reducer functions. As seen above.

//An action creator is a function that returns an action.